import { act, fireEvent, render, screen } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { App } from './App'
import * as services from './services'

beforeEach(() => { localStorage.clear(); vi.restoreAllMocks() })
const enter = (text: string) => fireEvent.change(screen.getByRole('textbox', { name: 'Originalprompt' }), { target: { value: text } })

describe('PromptRouter interactions', () => {
  it('analyzes, changes priority, and resets', async () => {
    const user = userEvent.setup()
    render(<App />)
    expect(screen.getByRole('button', { name: 'Analysieren' })).toBeDisabled()
    enter('2 + 2')
    await user.click(screen.getByRole('button', { name: 'Analysieren' }))
    expect(await screen.findByRole('heading', { name: 'Demo Balanced' })).toBeInTheDocument()
    await user.click(screen.getByRole('button', { name: /Fast/ }))
    expect(screen.getByRole('heading', { name: 'Demo Speed' })).toBeInTheDocument()
    await user.click(screen.getByRole('button', { name: 'Zurücksetzen' }))
    expect(screen.getByRole('textbox', { name: 'Originalprompt' })).toHaveValue('')
    expect(screen.getByRole('button', { name: /Balanced/ })).toHaveAttribute('aria-pressed', 'true')
    expect(screen.queryByRole('heading', { name: 'Demo Speed' })).not.toBeInTheDocument()
  })
  it('loads examples and clears results when the original changes', async () => {
    const user = userEvent.setup()
    render(<App />)
    await user.selectOptions(screen.getByLabelText('Oder starte mit einem Beispiel'), 'file')
    await user.click(screen.getByRole('button', { name: 'Analysieren' }))
    expect(await screen.findByRole('heading', { name: 'Demo Data' })).toBeInTheDocument()
    enter('Neue Eingabe')
    expect(screen.queryByRole('textbox', { name: 'Optimierter Prompt' })).not.toBeInTheDocument()
  })
  it('invalidates and reevaluates a manually edited prompt', async () => {
    const user = userEvent.setup()
    render(<App />)
    enter('2 + 2')
    await user.click(screen.getByRole('button', { name: 'Analysieren' }))
    await user.click(screen.getByRole('button', { name: 'Bearbeiten' }))
    fireEvent.change(screen.getByRole('textbox', { name: 'Optimierter Prompt' }), { target: { value: 'Recherchiere aktuelle Informationen mit verlässlichen Quellen.' } })
    expect(screen.queryByRole('heading', { name: 'Demo Balanced' })).not.toBeInTheDocument()
    await user.click(screen.getByRole('button', { name: /Übernehmen und neu bewerten/ }))
    expect(screen.getByRole('heading', { name: 'Demo Research' })).toBeInTheDocument()
    expect(screen.getByText('Basis: bearbeiteter Prompt')).toBeInTheDocument()
    expect(screen.getByRole('textbox', { name: 'Originalprompt' })).toHaveValue('2 + 2')
  })
  it('copies the visible text and honestly handles clipboard refusal', async () => {
    const user = userEvent.setup()
    const write = vi.spyOn(navigator.clipboard, 'writeText').mockResolvedValue()
    render(<App />)
    enter('2 + 2')
    await user.click(screen.getByRole('button', { name: 'Analysieren' }))
    await user.click(screen.getByRole('button', { name: 'Prompt kopieren' }))
    expect(write).toHaveBeenCalledWith('2 + 2')
    expect(screen.getByRole('status')).toHaveTextContent('Prompt kopiert.')
    write.mockRejectedValueOnce(new Error('denied'))
    await user.click(screen.getByRole('button', { name: 'Prompt kopieren' }))
    expect(screen.getByRole('status')).toHaveTextContent('Kopieren nicht erlaubt')
  })
  it('stores only theme preferences', async () => {
    const user = userEvent.setup()
    render(<App />)
    enter('Mein privater Prompt: 2 + 2')
    await user.click(screen.getByRole('button', { name: 'Analysieren' }))
    expect(localStorage.length).toBe(0)
    await user.click(screen.getByRole('button', { name: 'Dark Mode aktivieren' }))
    expect(localStorage.getItem('promptrouter-theme')).toBe('dark')
    expect(localStorage.length).toBe(1)
  })
  it('never truncates oversized input', () => {
    render(<App />)
    const text = 'x'.repeat(20_001)
    enter(text)
    expect(screen.getByRole('textbox', { name: 'Originalprompt' })).toHaveValue(text)
    expect(screen.getByRole('button', { name: 'Analysieren' })).toBeDisabled()
    expect(screen.getByRole('alert')).toHaveTextContent('20.000')
  })
  it('discards a late result after the input changes', async () => {
    const user = userEvent.setup()
    const oldResult = await services.processPrompt({ text: '2 + 2', revision: 1 })
    let resolve!: (value: typeof oldResult) => void
    vi.spyOn(services, 'processPrompt').mockImplementationOnce(() => new Promise((done) => { resolve = done }))
    render(<App />)
    enter('2 + 2')
    await user.click(screen.getByRole('button', { name: 'Analysieren' }))
    enter('Build a React project.')
    await act(async () => { resolve(oldResult) })
    expect(screen.queryByRole('heading', { name: 'Demo Balanced' })).not.toBeInTheDocument()
    expect(screen.queryByRole('textbox', { name: 'Optimierter Prompt' })).not.toBeInTheDocument()
  })
  it('analyzes with Ctrl+Enter and explains the category', async () => {
    const user = userEvent.setup()
    render(<App />)
    await user.click(screen.getByRole('textbox', { name: 'Originalprompt' }))
    await user.keyboard('Berechne 17 * 24.{Control>}{Enter}{/Control}')
    expect(await screen.findByText('Warum diese Kategorie?')).toBeInTheDocument()
    expect(screen.getByText(/Rechenausdruck · Mathematik \+3/)).toBeInTheDocument()
    expect(screen.getByText(/Erkannt · \d+ %/)).toBeInTheDocument()
    expect(screen.getByText(/^Analyse fertig: Mathematik\. Empfehlung: Demo Balanced\.$/)).toBeInTheDocument()
  })
  it('labels a fallback route instead of giving no recommendation', async () => {
    const user = userEvent.setup()
    render(<App />)
    enter('What is the capital of France?')
    await user.click(screen.getByRole('button', { name: 'Analysieren' }))
    expect(await screen.findByRole('heading', { name: 'Demo Balanced' })).toBeInTheDocument()
    expect(screen.getByText('Allgemein · Fallback')).toBeInTheDocument()
    expect(screen.getByText('Fallback-Empfehlung')).toBeInTheDocument()
  })
})
